Attribute VB_Name = "Constants"
Option Explicit

Public Const ENEMYDATA_ORIGINAL_OFFSET As Long = &H1B1A66

Public Const ENEMYGOLD_ORIGINAL_OFFSET As Long = &HBECC&


Public Const ITEMDEFS_ORIGINAL_OFFSET As Long = &H16EA6


Public Const CLASSDATAPOINTER_ORIGINAL_OFFSET As Long = &H1EE00C
Public Const CLASSDATA_ORIGINAL_OFFSET As Long = &H1EE890

Public Const CLASSNAMES_ORIGINAL_OFFSET As Long = &H17F3E

Public Const BATTLESPRITES_ORIGINAL_OFFSET As Long = &H1F806


Public Const SPELLDEFS_ORIGINAL_OFFSET As Long = &H176A6


Public Const ITEMNAMES_ORIGINAL_OFFSET As Long = &H1796E


Public Const SPELLNAMES_ORIGINAL_OFFSET As Long = &HF9C4&


Public Const ALLYNAMES_ORIGINAL_OFFSET As Long = &HFAD6&


Public Const ENEMYNAMES_ORIGINAL_OFFSET As Long = &HFB8A&

Public Const ALLYSTARTDATAPOINTER_ORIGINAL_OFFSET As Long = &H1EE008
Public Const ALLYSTARTDATA_ORIGINAL_OFFSET As Long = &H1EE7D0


Public Const ALLYSTATS_ORIGINAL_OFFSET As Long = &H1EE270
Public Const ALLYSTATSDATASTART_ORIGINAL_OFFSET As Long = &H1EE2F0


Public Const PROMOTIONS_ORIGINAL_OFFSET As Long = &H21046


Public Const SHOPITEMS_ORIGINAL_OFFSET As Long = &H20878
Public Const SHOPITEMS_ORIGINAL_LENGTH As Long = &H18A

Public Const JEWELENDSCREENLAYOUTPOINTER_ORIGINAL_OFFSET As Long = &H1EE014
Public Const JEWELENDSCREENLAYOUT_ORIGINAL_OFFSET As Long = &H1EE930


Public Const MAXLEVEL_ORIGINAL_OFFSET As Long = &H949B&
Public Const MAXLEVELUNPROMOTED_ORIGINAL_OFFSET As Long = &H94A3&

Public Const PROMOTIONLEVEL_ORIGINAL_OFFSET As Long = &H20DB7








